name: Valist Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Build and export Create React App
        run: |
          cd client
          npm install
          npm run build

      - name: Mark Timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        
      - name: Valist Publish
        uses: valist-io/valist-github-action@v2.6.2
        with:
          private-key: ${{ secrets.VALIST_SIGNER }}
          account: powrd
          project: powrd
          release: ${{ env.TIMESTAMP }}
          platform-web: client/dist
        
